name: Daily News Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: تحميل الملفات
        uses: actions/checkout@v4

      - name: إعداد Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: تثبيت المتطلبات
        run: pip install -r requirements.txt

      - name: تشغيل البوت
        run: python bot.py
